train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        min_gain_in_db: -6.0
        max_gain_in_db: 3.0
        p: 0.5
      - _target_: src.transforms.wav_augs.PitchShift
        min_semitones: -4.0
        max_semitones: 4.0
        p: 0.5
      - _target_: src.transforms.wav_augs.AddWhiteNoise
        amplitude: 0.01
        p: 0.5
      - _target_: src.transforms.wav_augs.PolarityInversion
        p: 0.5
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
